In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.10.0'

## Constantes

### Definindo uma constante

In [5]:
# definindo uma constante no tensorflow
tensor = tf.constant([[23, 24], [32, 51]])

In [6]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 24],
       [32, 51]], dtype=int32)>

In [7]:
tensor.shape 

TensorShape([2, 2])

### Acessonda os valores de uma constante

In [8]:
tensor.numpy()

array([[23, 24],
       [32, 51]], dtype=int32)

In [9]:
# converter um array numpy para um tensor 
numpy_tensor = np.array([[23, 4], [32, 51]])

In [10]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy 

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

## Variaveis

### Definindo uma variavel

In [12]:
tf_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Acessando os valores de uma variavel

In [13]:
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Alterando um valor especifico de uma variavel

In [14]:
tf_variable[0, 2].assign(100)
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## Operacoes com tensores

In [15]:
tensor_1 = tf.constant([[1, 2],[3, 4]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Adicao entre um escalar e um tensor 

In [17]:
tensor_1 + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

### Multiplicacao entre um escalar e um tensor

In [18]:
tensor_1 * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

### Usando funcoes do numpy em tensores

In [19]:
# Obtendo o quadrado de todos os membros de um tensor 
np.square(tensor)

array([[ 529,  576],
       [1024, 2601]], dtype=int32)

In [20]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[4.79583152, 4.89897949],
       [5.65685425, 7.14142843]])

### Produto escalar entre dois tensores

In [22]:
np.dot(tensor, tensor_1)

array([[ 95, 142],
       [185, 268]], dtype=int32)

## Strings no TensorFlow

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

### Operacoes simples com string

In [25]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [26]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Armazenando arrays (vetores) de string

In [27]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [28]:
for string in tf_string_array:
    print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
